Repository mimblewimble/grin-rfcs, pull requests merged in 2019-12, with the labels that each got.

#28 Node API V2
  text/0007-node-api-v2.md
Labels: core, node dev

#35 Cleanup numbering, add to README and remove 'Edit if merged'
  README.md
  text/0003-security-process.md
  text/0007-node-api-v2.md
  text/0008-wallet-state-management.md
Labels: enhancement

#29 Enable faster sync
  text/0009-enable-faster-sync.md
Labels: core, enhancement, node dev

#24 Online Transacting via TOR Hidden Services
  text/0000-online-transacting-via-tor.md
Labels: wallet dev
